// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Context.Models.Travel;

namespace Travel.Context.Migrations.Travel
{
    [DbContext(typeof(TravelContext))]
    partial class TravelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Travel.Context.Models.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdImage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Travel.Context.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountSeat")
                        .HasColumnType("int");

                    b.Property<string>("LiscensePlate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NameDriver")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Travel.Context.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpDate")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdFile")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdService")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<long>("SignDate")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeService")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Travel.Context.Models.CostTour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Breakfast")
                        .HasColumnType("real");

                    b.Property<int>("CusExpected")
                        .HasColumnType("int");

                    b.Property<float>("Depreciation")
                        .HasColumnType("real");

                    b.Property<float>("Distance")
                        .HasColumnType("real");

                    b.Property<float>("FeeGas")
                        .HasColumnType("real");

                    b.Property<Guid>("IdHotel")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPlace")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRestaurant")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdTourDetail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("InsuranceFee")
                        .HasColumnType("real");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<float>("OtherPrice")
                        .HasColumnType("real");

                    b.Property<float>("PriceHotel")
                        .HasColumnType("real");

                    b.Property<float>("PriceRestaurant")
                        .HasColumnType("real");

                    b.Property<float>("PriceTicketPlace")
                        .HasColumnType("real");

                    b.Property<float>("SellCost")
                        .HasColumnType("real");

                    b.Property<float>("Tolls")
                        .HasColumnType("real");

                    b.Property<float>("TotalCostTour")
                        .HasColumnType("real");

                    b.Property<float>("Water")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IdHotel");

                    b.HasIndex("IdPlace");

                    b.HasIndex("IdRestaurant");

                    b.HasIndex("IdTourDetail")
                        .IsUnique()
                        .HasFilter("[IdTourDetail] IS NOT NULL");

                    b.ToTable("CostTours");
                });

            modelBuilder.Entity("Travel.Context.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Birthday")
                        .HasColumnType("bigint");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FbToken")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GoogleToken")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Travel.Context.Models.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProvice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvice");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Travel.Context.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.Property<long>("Birthday")
                        .HasColumnType("bigint");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("0");

                    b.Property<string>("IdSchedule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Travel.Context.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Travel.Context.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("DoubleRoomPrice")
                        .HasColumnType("real");

                    b.Property<Guid>("IdContract")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("QuantityDBR")
                        .HasColumnType("int");

                    b.Property<int>("QuantitySR")
                        .HasColumnType("int");

                    b.Property<float>("SingleRoomPrice")
                        .HasColumnType("real");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Travel.Context.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("IdService")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Travel.Context.Models.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IdTourBooking")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdTourBooking");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Travel.Context.Models.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdContract")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<float>("PriceTicket")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Travel.Context.Models.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("FromDate")
                        .HasColumnType("bigint");

                    b.Property<string>("IdSchedule")
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ToDate")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSchedule");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Travel.Context.Models.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Travel.Context.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdContract")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Travel.Context.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Travel.Context.Models.Schedule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("BeginDate")
                        .HasColumnType("bigint");

                    b.Property<long>("DepartureDate")
                        .HasColumnType("bigint");

                    b.Property<long>("EndDate")
                        .HasColumnType("bigint");

                    b.Property<float>("FinalPrice")
                        .HasColumnType("real");

                    b.Property<Guid>("IdCar")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdPromotion")
                        .HasColumnType("int");

                    b.Property<string>("IdTour")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("MinCapacity")
                        .HasColumnType("real");

                    b.Property<float>("QuantityAdult")
                        .HasColumnType("real");

                    b.Property<float>("QuantityBaby")
                        .HasColumnType("real");

                    b.Property<float>("QuantityChild")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TimePromotion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdCar");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdTour");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Travel.Context.Models.Timeline", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("FromTime")
                        .HasColumnType("bigint");

                    b.Property<string>("IdSchedule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<long>("ToTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdSchedule");

                    b.ToTable("Timelines");
                });

            modelBuilder.Entity("Travel.Context.Models.Tour", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApproveStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint");

                    b.Property<string>("FromPlace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Thumbsnail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToPlace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("Travel.Context.Models.TourDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<float>("DisplayPrice")
                        .HasColumnType("real");

                    b.Property<float>("DisplayPromotionPrice")
                        .HasColumnType("real");

                    b.Property<float>("FinalPrice")
                        .HasColumnType("real");

                    b.Property<Guid>("IdCostTour")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPromotion")
                        .HasColumnType("bit");

                    b.Property<float>("PriceAdult")
                        .HasColumnType("real");

                    b.Property<float>("PriceAdultPromotion")
                        .HasColumnType("real");

                    b.Property<float>("PriceBaby")
                        .HasColumnType("real");

                    b.Property<float>("PriceBabyPromotion")
                        .HasColumnType("real");

                    b.Property<float>("PriceChild")
                        .HasColumnType("real");

                    b.Property<float>("PriceChildPromotion")
                        .HasColumnType("real");

                    b.Property<int>("Profit")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBooked")
                        .HasColumnType("int");

                    b.Property<float>("TotalCostTour")
                        .HasColumnType("real");

                    b.Property<string>("TourId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Vat")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TourDetails");
                });

            modelBuilder.Entity("Travel.Context.Models.Tourbooking", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BookingNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("DateBooking")
                        .HasColumnType("bigint");

                    b.Property<float>("Deposit")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCalled")
                        .HasColumnType("bit");

                    b.Property<long>("LastDate")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float>("RemainPrice")
                        .HasColumnType("real");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.Property<double>("Vat")
                        .HasColumnType("float");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Tourbookings");
                });

            modelBuilder.Entity("Travel.Context.Models.TourbookingDetails", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Adult")
                        .HasColumnType("int");

                    b.Property<int>("Baby")
                        .HasColumnType("int");

                    b.Property<long>("CallDate")
                        .HasColumnType("bigint");

                    b.Property<int>("Child")
                        .HasColumnType("int");

                    b.Property<string>("IdTourBooking")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsCalled")
                        .HasColumnType("bit");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTourBooking")
                        .IsUnique()
                        .HasFilter("[IdTourBooking] IS NOT NULL");

                    b.ToTable("tourbookingDetails");
                });

            modelBuilder.Entity("Travel.Context.Models.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("EndDate")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdCustomer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint");

                    b.Property<int>("Point")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("StartDate")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Travel.Context.Models.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDistrict")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdDistrict");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Travel.Context.Models.CostTour", b =>
                {
                    b.HasOne("Travel.Context.Models.Hotel", "Hotel")
                        .WithMany("CostTours")
                        .HasForeignKey("IdHotel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Context.Models.Place", "Place")
                        .WithMany("CostTours")
                        .HasForeignKey("IdPlace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Context.Models.Restaurant", "Restaurant")
                        .WithMany("CostTours")
                        .HasForeignKey("IdRestaurant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Context.Models.TourDetail", "TourDetails")
                        .WithOne("CostTour")
                        .HasForeignKey("Travel.Context.Models.CostTour", "IdTourDetail");

                    b.Navigation("Hotel");

                    b.Navigation("Place");

                    b.Navigation("Restaurant");

                    b.Navigation("TourDetails");
                });

            modelBuilder.Entity("Travel.Context.Models.District", b =>
                {
                    b.HasOne("Travel.Context.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("IdProvice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Travel.Context.Models.Employee", b =>
                {
                    b.HasOne("Travel.Context.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Travel.Context.Models.Payment", b =>
                {
                    b.HasOne("Travel.Context.Models.Tourbooking", "Tourbooking")
                        .WithMany("Payment")
                        .HasForeignKey("IdTourBooking");

                    b.Navigation("Tourbooking");
                });

            modelBuilder.Entity("Travel.Context.Models.Promotion", b =>
                {
                    b.HasOne("Travel.Context.Models.Schedule", "Schedules")
                        .WithMany("Promotions")
                        .HasForeignKey("IdSchedule");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Travel.Context.Models.Schedule", b =>
                {
                    b.HasOne("Travel.Context.Models.Car", "Cars")
                        .WithMany("Schedules")
                        .HasForeignKey("IdCar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Context.Models.Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Context.Models.Tour", "Tour")
                        .WithMany("Schedules")
                        .HasForeignKey("IdTour");

                    b.Navigation("Cars");

                    b.Navigation("Employee");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Travel.Context.Models.Timeline", b =>
                {
                    b.HasOne("Travel.Context.Models.Schedule", "Schedule")
                        .WithMany("Timelines")
                        .HasForeignKey("IdSchedule");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Travel.Context.Models.TourbookingDetails", b =>
                {
                    b.HasOne("Travel.Context.Models.Tourbooking", "Tourbooking")
                        .WithOne("TourbookingDetails")
                        .HasForeignKey("Travel.Context.Models.TourbookingDetails", "IdTourBooking");

                    b.Navigation("Tourbooking");
                });

            modelBuilder.Entity("Travel.Context.Models.Ward", b =>
                {
                    b.HasOne("Travel.Context.Models.District", "District")
                        .WithMany("Ward")
                        .HasForeignKey("IdDistrict")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Travel.Context.Models.Car", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Travel.Context.Models.District", b =>
                {
                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Travel.Context.Models.Employee", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Travel.Context.Models.Hotel", b =>
                {
                    b.Navigation("CostTours");
                });

            modelBuilder.Entity("Travel.Context.Models.Place", b =>
                {
                    b.Navigation("CostTours");
                });

            modelBuilder.Entity("Travel.Context.Models.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Travel.Context.Models.Restaurant", b =>
                {
                    b.Navigation("CostTours");
                });

            modelBuilder.Entity("Travel.Context.Models.Schedule", b =>
                {
                    b.Navigation("Promotions");

                    b.Navigation("Timelines");
                });

            modelBuilder.Entity("Travel.Context.Models.Tour", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Travel.Context.Models.TourDetail", b =>
                {
                    b.Navigation("CostTour");
                });

            modelBuilder.Entity("Travel.Context.Models.Tourbooking", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("TourbookingDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
